openapi: 3.0.3
info:
  title: Resivate API
  description: A FastAPI project for resivate
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/categories:
    get:
      operationId: read_categories
      summary: Get All Categories
      description: Retrieve a list of all categories
      parameters:
        - name: skip
          in: query
          description: Number of records to skip
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          description: Maximum number of records to return
          required: false
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      operationId: create_category
      summary: Create Category
      description: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        '201':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /api/categories/{category_id}:
    get:
      operationId: read_category
      summary: Get Category
      description: Get a specific category by ID
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
    put:
      operationId: update_category
      summary: Update Category
      description: Update an existing category
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
    delete:
      operationId: delete_category
      summary: Delete Category
      description: Delete a category
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
      responses:
        '204':
          description: Category deleted
        '404':
          description: Category not found
components:
  schemas:
    CategoryBase:
      type: object
      required:
        - title
        - link
      properties:
        title:
          type: string
          description: Category title
          maxLength: 255
          minLength: 1
        link:
          type: string
          description: Category link
          maxLength: 512
          minLength: 1
    CategoryCreate:
      allOf:
        - $ref: '#/components/schemas/CategoryBase'
    CategoryUpdate:
      type: object
      properties:
        title:
          type: string
          description: Category title
          maxLength: 255
          minLength: 1
        link:
          type: string
          description: Category link
          maxLength: 512
          minLength: 1
    Category:
      allOf:
        - $ref: '#/components/schemas/CategoryBase'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              description: Category ID 